#!/usr/bin/env python3
"""Export carousel HTML files to PNGs using headless Chromium (Playwright).

Takes direct path(s) to HTML file(s) and/or directories — fully dynamic,
no fixed content registry or carousel-ID lookup. Run AFTER reviewing and
approving HTML generated by generate.py (or written directly via
template.build_carousel()).

Usage:
  python export.py my_carousel.html                       # one file
  python export.py carousel_a.html carousel_b.html         # multiple files
  python export.py html/                                   # every .html in a directory
  python export.py html/ --out /path/to/output/            # custom output dir

Requirements:
  pip install playwright
  playwright install chromium
"""
import argparse
import asyncio
from pathlib import Path

from playwright.async_api import async_playwright

VIEW_W, VIEW_H = 420, 525
SCALE = 1080 / 420

STRIP_JS = """() => {
  document.querySelectorAll('.ig-header,.ig-dots,.ig-actions,.ig-caption')
    .forEach(el => el.style.display = 'none');
  const frame = document.querySelector('.ig-frame');
  if (frame) frame.style.cssText =
    'width:420px;height:525px;max-width:none;border-radius:0;box-shadow:none;overflow:hidden;margin:0;';
  const vp = document.querySelector('.carousel-viewport');
  if (vp) vp.style.cssText =
    'width:420px;height:525px;aspect-ratio:unset;overflow:hidden;cursor:default;';
  document.body.style.cssText =
    'padding:0;margin:0;display:block;overflow:hidden;background:#fff;';
}"""


def _collect_html_files(paths: list[Path]) -> list[Path]:
    files = []
    for p in paths:
        if p.is_dir():
            files.extend(sorted(p.glob("*.html")))
        elif p.suffix == ".html" and p.is_file():
            files.append(p)
        else:
            print(f"Warning: skipping (not an HTML file or directory): {p}")
    return files


async def export(html_paths: list[Path], out_base: Path):
    html_files = _collect_html_files(html_paths)

    if not html_files:
        print("No HTML files found at the given path(s).")
        return

    print(f"Exporting {len(html_files)} carousel(s)...\n")

    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page(
            viewport={"width": VIEW_W, "height": VIEW_H},
            device_scale_factor=SCALE,
        )
        for html_path in html_files:
            out_dir = out_base / html_path.stem
            out_dir.mkdir(parents=True, exist_ok=True)
            await page.goto(f"file://{html_path.resolve()}", wait_until="networkidle")
            await page.wait_for_timeout(3000)
            n = await page.evaluate(
                "() => document.querySelector('.carousel-track')?.children.length || 0"
            )
            await page.evaluate(STRIP_JS)
            await page.wait_for_timeout(200)
            for i in range(n):
                offset = -i * 420
                await page.evaluate(
                    f"() => {{ const t = document.querySelector('.carousel-track'); "
                    f"t.style.transition='none'; t.style.transform='translateX({offset}px)'; }}"
                )
                await page.wait_for_timeout(400)
                await page.screenshot(
                    path=str(out_dir / f"slide_{i + 1}.png"),
                    clip={"x": 0, "y": 0, "width": VIEW_W, "height": VIEW_H},
                )
            print(f"  ✓ {html_path.stem} ({n} slides)")
        await browser.close()

    total = sum(1 for _ in out_base.rglob("*.png"))
    print(f"\nDone. {total} total PNG(s) in {out_base}/")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export carousel HTML → PNG")
    parser.add_argument(
        "paths",
        nargs="+",
        type=Path,
        metavar="PATH",
        help="HTML file(s) and/or directory(ies) containing HTML files",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).parent / "output",
        metavar="PATH",
        help="Output directory for PNGs (default: scripts/output/)",
    )
    args = parser.parse_args()
    asyncio.run(export(html_paths=args.paths, out_base=args.out))
