#!/usr/bin/env python3
"""Export carousel HTML files to PNGs using headless Chromium (Playwright).

Run AFTER reviewing and approving the HTML files generated by generate.py.

Usage:
  python export.py                                  # export all carousels in html/
  python export.py --carousel c07_big_5_lifts  # one carousel only
  python export.py --carousel c09_habit_stacking c13_alcohol_honest_math  # multiple
  python export.py --html-dir /path/to/html/        # custom HTML directory

Requirements:
  pip install playwright
  playwright install chromium
"""
import argparse
import asyncio
from pathlib import Path

from playwright.async_api import async_playwright

VIEW_W, VIEW_H = 420, 525
SCALE = 1080 / 420

STRIP_JS = """() => {
  document.querySelectorAll('.ig-header,.ig-dots,.ig-actions,.ig-caption')
    .forEach(el => el.style.display = 'none');
  const frame = document.querySelector('.ig-frame');
  if (frame) frame.style.cssText =
    'width:420px;height:525px;max-width:none;border-radius:0;box-shadow:none;overflow:hidden;margin:0;';
  const vp = document.querySelector('.carousel-viewport');
  if (vp) vp.style.cssText =
    'width:420px;height:525px;aspect-ratio:unset;overflow:hidden;cursor:default;';
  document.body.style.cssText =
    'padding:0;margin:0;display:block;overflow:hidden;background:#fff;';
}"""


async def export(html_dir: Path, carousel_ids: list[str] | None = None):
    out_base = html_dir.parent / "output"
    html_files = sorted(html_dir.glob("*.html"))

    if carousel_ids:
        html_files = [f for f in html_files if f.stem in carousel_ids]
        missing = set(carousel_ids) - {f.stem for f in html_files}
        if missing:
            print(f"Warning: no HTML found for: {', '.join(sorted(missing))}")

    if not html_files:
        print("No HTML files to export.")
        return

    print(f"Exporting {len(html_files)} carousel(s)...\n")

    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page(
            viewport={"width": VIEW_W, "height": VIEW_H},
            device_scale_factor=SCALE,
        )
        for html_path in html_files:
            out_dir = out_base / html_path.stem
            out_dir.mkdir(parents=True, exist_ok=True)
            await page.goto(f"file://{html_path.resolve()}", wait_until="networkidle")
            await page.wait_for_timeout(3000)
            n = await page.evaluate(
                "() => document.querySelector('.carousel-track')?.children.length || 0"
            )
            await page.evaluate(STRIP_JS)
            await page.wait_for_timeout(200)
            for i in range(n):
                offset = -i * 420
                await page.evaluate(
                    f"() => {{ const t = document.querySelector('.carousel-track'); "
                    f"t.style.transition='none'; t.style.transform='translateX({offset}px)'; }}"
                )
                await page.wait_for_timeout(400)
                await page.screenshot(
                    path=str(out_dir / f"slide_{i + 1}.png"),
                    clip={"x": 0, "y": 0, "width": VIEW_W, "height": VIEW_H},
                )
            print(f"  ✓ {html_path.stem} ({n} slides)")
        await browser.close()

    total = sum(1 for _ in out_base.rglob("*.png"))
    print(f"\nDone. {total} total PNG(s) in {out_base}/")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export carousel HTML → PNG")
    parser.add_argument(
        "--carousel",
        nargs="+",
        metavar="ID",
        help="Export specific carousel(s) by ID (e.g. c07_big_5_lifts)",
    )
    parser.add_argument(
        "--html-dir",
        type=Path,
        default=Path(__file__).parent / "html",
        metavar="PATH",
        help="Directory containing generated HTML files (default: scripts/html/)",
    )
    args = parser.parse_args()
    asyncio.run(export(html_dir=args.html_dir, carousel_ids=args.carousel))
